function calibration_outcomes(data, parameters, model_data, result_path)

% Function that produces parameter and model fit tables (table 1 and table
% 2) and figures showing model fit to data (figures 4 and 5) 

% arguments: data: CPS data structure; parameters: structure with model parameters;
% model_data: model precited moments; result_path: location of folder with results 


%% 1. TABLES

% rename parameter structure  arguments for convenience
d = data; p = parameters; m = model_data; 
clearvars data parameters model_data 

% table path
tables_path = [result_path,'\Tables\'];

%% 1.1. Parameter tables (table 1)

% compute mu_x
p.mu_x = -p.sigma_x^2/2; 

% number format
format = '%.3f';

% build table
Table_1 = [ ...
    '\\begin{table}[!h]'        '\n' ...
    '\\small'        '\n' ...
    '\\centering'        '\n' ...
    '\\captionof{table}{Calibrated parameter values}'        '\n' ...
    '\\label{tab:table_1}'        '\n' ...
    '\\begin{tabular}{l  l  c}'        '\n' ...
    '\\hline \\hline'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\multicolumn{ 3 }{l}{\\textit{Preset / normalizations}}   \\\\'        '\n' ...
    '\\addlinespace'        '\n' ...
    '$\\beta$   \\hspace{30pt}  & discount factor \\hspace{175pt} &',    '0.9967',  '\\\\'        '\n' ...
    '$\\gamma$                  & worker''s bargaining power &',         '0.3',     '\\\\'        '\n' ...
    '$\\eta$                    & elasticity of matching function &',    '0.5',     '\\\\'        '\n' ...
    '$\\delta$                  & exogenous separation &',               '0.0039',  '\\\\'        '\n' ...
    '$[\\underline{z},\\overline{z}]$   & support of stochastic output component & [0,1] \\\\'        '\n' ...
    '$\\mu_x$                   & mean of log match quality &',          num2str(p.mu_x, format),   '\\\\'        '\n' ...
    '$\\mu_{u,y}$               & unemployment log-skill mean &',        '0',                       '\\\\'        '\n' ...
    '$\\chi$                    & skill-match quality complementarity &','1',                       '\\\\'        '\n' ...
    '$F$                        & firing costs &',                       '0',                       '\\\\'        '\n' ...
    '$\\phi$                    & output tax &',                         '0',                       '\\\\'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\multicolumn{ 3 }{l}{\\textit{Internal}}   \\\\'        '\n' ...
    '\\addlinespace'        '\n' ...
    '$A$              & efficiency of matching &',            num2str(p.A, format),         '\\\\'        '\n' ...
    '$c_v$            & vacancy-posting cost &',              num2str(p.c_v, format),    '\\\\'        '\n' ...
    '$b$              & non-work income        &',            num2str(p.b, format),         '\\\\'        '\n' ...
    '$\\xi$           & EE relative search efficiency &',     num2str(p.s, format),         '\\\\'        '\n' ...
    '$\\lambda$       & probability of match output shock &', num2str(p.lambda, format),    '\\\\'        '\n' ...
    '$\\sigma_x^2$    & log match quality variance &',        num2str(p.sigma_x^2, format), '\\\\'        '\n' ...
    '$\\kappa$        & search cost, linear component &',     num2str(p.c0, format),        '\\\\'        '\n' ...
    '$\\underline{s}$ & passive-search threshold &',          num2str(p.slb, format),       '\\\\'        '\n' ...
    '$\\mu_{e,y}$     & employment log-skill mean &',         num2str(p.mu1, format),       '\\\\'        '\n' ...
    '$\\rho_y$        & log-skill persistence &',             num2str(p.rho_a, format),     '\\\\'        '\n' ...
    '$\\sigma_{\\varepsilon}^2$  & log-skill disturbance variance &',    num2str(p.sigma_a^2, format), '\\\\'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\addlinespace'        '\n' ...
    '\\hline \\hline'       '\n' ...
    '\\end{tabular}'         '\n' ...
    '\\caption*{\\footnotesize{\\textit{Notes:} calibrated parameter values. See table \\ref{tab:table_2} for targeted calibration statistics.',  '\n' ...
    '  }}' '\n' ...
    '\\end{table}' ];

% Export table to result folder
fileID = fopen([tables_path, 'Table_1.tex'],'w');
fprintf(fileID, Table_1);
fclose(fileID);



%% 1.2. Model fit table (table 2)

format = '%.2f';

calibration_targets = d.calibration_targets;

% vectors 
ue = [ calibration_targets.ue,  m.agg.ue ]*100;         
eu = [ calibration_targets.eu,  m.agg.eu ]*100; 
ee = [ calibration_targets.ee,  m.agg.ee ]*100; 
var_w = [ calibration_targets.var_w,  m.agg.var_w ]; 

ue_2024 = [ calibration_targets.ue_2024,  m.agg.ue_2024 ]*100;
ue_2529 = [ calibration_targets.ue_2529,  m.agg.ue_2529 ]*100;
ue_3039 = [ calibration_targets.ue_3039,  m.agg.ue_3039 ]*100;
ue_4049 = [ calibration_targets.ue_4049,  m.agg.ue_4049 ]*100;
ue_5054 = [ calibration_targets.ue_5054,  m.agg.ue_5054 ]*100;

eu_2024 = [ calibration_targets.eu_2024,  m.agg.eu_2024 ]*100;
eu_2529 = [ calibration_targets.eu_2529,  m.agg.eu_2529 ]*100;
eu_3039 = [ calibration_targets.eu_3039,  m.agg.eu_3039 ]*100;
eu_4049 = [ calibration_targets.eu_4049,  m.agg.eu_4049 ]*100;
eu_5054 = [ calibration_targets.eu_5054,  m.agg.eu_5054 ]*100;


Table_2 = [ ...
'\\begin{table}[!h]'        '\n' ...
'\\small'        '\n' ...
'\\centering'        '\n' ...
'\\captionof{table}{Targeted data and model aggregate statistics}'        '\n' ...
'\\label{tab:table_2}'        '\n' ...
'\\begin{tabular}{l c c}'        '\n' ...
'\\hline \\hline'        '\n' ...
'\\addlinespace'        '\n' ...
'& \\text{Data} & \\text{Model} \\\\'        '\n' ...
'\\textit{Aggregate transition rates (\\%%)}  \\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{0.5cm} UE \\hspace{6.5cm}  &' num2str(ue(1), format) ' & ' num2str(ue(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} EU                 &' num2str(eu(1), format) ' & ' num2str(eu(2), format)  '\\\\'        '\n' ...
'\\hspace{0.5cm} EE                 &' num2str(ee(1), format) ' & ' num2str(ee(2), format)  '\\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\textit{log-wage variance}        &' num2str(var_w(1), '%.4f') ' & ' num2str(var_w(2), '%.4f') '\\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\textit{Age-specific UE transition probability (\\%%)} \\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{0.5cm} 20-24  &' num2str(ue_2024(1), format) ' & ' num2str(ue_2024(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 25-29  &' num2str(ue_2529(1), format) ' & ' num2str(ue_2529(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 30-39  &' num2str(ue_3039(1), format) ' & ' num2str(ue_3039(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 40-49  &' num2str(ue_4049(1), format) ' & ' num2str(ue_4049(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 50-54  &' num2str(ue_5054(1), format) ' & ' num2str(ue_5054(2), format) '\\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\textit{Age-specific EU transition probability (\\%%)} \\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{0.5cm} 20-24  &' num2str(eu_2024(1), format) ' & ' num2str(eu_2024(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 25-29  &' num2str(eu_2529(1), format) ' & ' num2str(eu_2529(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 30-39  &' num2str(eu_3039(1), format) ' & ' num2str(eu_3039(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 40-49  &' num2str(eu_4049(1), format) ' & ' num2str(eu_4049(2), format) '\\\\'        '\n' ...
'\\hspace{0.5cm} 50-54  &' num2str(eu_5054(1), format) ' & ' num2str(eu_5054(2), format) '\\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\hline \\hline'        '\n' ...
'\\end{tabular}'         '\n' ...
'\\caption*{\\footnotesize{\\textit{Notes:} empirical targeted and model statistics.', '\n' ...
'Data source: IPUMS CPS, 1995-2018. UE, EU, and EE aggregate monthly rates and age profile of the UE and EU rates are computed from Basic Monthly CPS worker-flow data.',  '\n' ...
'The log-wage variance is computed from Ongoing Rotation Group data. See data appendix \\ref{appendix:data}. }}',   '\n' ...
'\\end{table}' ];


% Export table to result folder
fileID = fopen([tables_path, 'Table_2.tex'],'w');
fprintf(fileID, Table_2);
fclose(fileID);


%% 2. FIGURES

% figure path
figure_path = [result_path,'\Figures\'];

% age in years 
ix1 = 2; ix2 = 42;
age = 18 + (ix1:ix2);

% EE experience
y3 = [ d.age.ee(ix1:ix2), m.age.ee(ix1:ix2) ];

% UE, u duration
id1 = 2; id2 = 24;
dur = id1:id2;
y4 = [ d.udur.ue(id1:id2), m.udur.ue(id1:id2) ];

% EU, tenure
it1 = 1; it2 = 20;
ten = it1:it2;
y5 = [ d.ten.eu(it1:it2), m.ten.eu(it1:it2) ];

% EE, tenure
y6 = [ d.ten.ee(it1:it2), m.ten.ee(it1:it2) ];


%% 2.2. Figure 4

% EE, age
subplot('Position', [0.1 0.55 0.35 0.35])
hold on 

plot( age, y3(:,1)', 'o', 'Color', '#0D16A0', 'LineWidth', 1, 'MarkerSize', 4 )
plot( age, y3(:,2)', '-', 'Color', '#5AA2E3', 'LineWidth', 2 )

axis([18+ix1 18+ix2 .00 .075]); grid('on'); box('on'); title('(a) EE, age (years)', 'Interpreter', 'latex')

hold off


% UE, unemployment duration
subplot('Position', [0.55 0.55 0.35 0.35])
hold on

plot( dur, y4(:,1)', 'o', 'Color', '#0D16A0', 'LineWidth', 1, 'MarkerSize', 4 )
plot( dur, y4(:,2)', '-', 'Color', '#5AA2E3', 'LineWidth', 2.5 )

axis([id1 id2 .00 0.5]); grid('on'); box('on'); title('(b) UE, u duration (months)', 'Interpreter', 'latex' )
hold off

% EU, tenure
subplot('Position', [0.10 0.10 0.35 0.35])
hold on

plot( ten, y5(:,1)', 'o', 'Color', '#0D16A0', 'LineWidth', 1, 'MarkerSize', 4 )
plot( ten, y5(:,2)', '-', 'Color', '#5AA2E3', 'LineWidth', 2 )

axis([it1 it2 .0 0.075]); grid('on'); box('on'); title('(c) EU, tenure (years)', 'Interpreter', 'latex' )
hold off

% EE, tenure
subplot('Position', [0.55 0.10 0.35 0.35])
hold on 

plot( ten, y6(:,1)', 'o', 'Color', '#0D16A0', 'LineWidth', 1, 'MarkerSize', 4 )
plot( ten, y6(:,2)', '-', 'Color', '#5AA2E3', 'LineWidth', 2 )

axis([it1 it2 .0 0.075]); grid('on'); box('on'); title('(e) EE, tenure (years)', 'Interpreter', 'latex' )
legend( 'data', 'model', 'Interpreter', 'latex' ); legend('boxoff')
hold off

% export figure
saveas(gcf, [figure_path, '\Figure_4'], 'epsc')
saveas(gcf, [figure_path, '\Figure_4'], 'png')


end