%% 1. Calibration, alt model [optional]
% run('Calibration\Alternative_model_calibration.m')

%% 2. Run programs for accounting exercises
disp('Run programs for computations required for accounting exercise')
disp('')
disp('***')

% (i) benchmark, full model
disp('Benchmark model')
load("Results\Benchmark.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\Benchmark.mat", "table_accounting", '-append')
disp('***')

% (ii) alt model 1: no worker het.
disp('Alt model 1 (no worker het.)')
load("Results\alternative_models\model_1.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\alternative_models\model_1.mat", "table_accounting", '-append')
disp('***')

% (iii) alt model 2: no job het.
disp('Alt model 2 (no job het.)')
load("Results\alternative_models\model_2.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\alternative_models\model_2.mat", "table_accounting", '-append')
disp('***')

% (iv) alt model 3: no worker, job het.
disp('Alt model 3 (no worker/job het.)')
load("Results\alternative_models\model_3.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\alternative_models\model_3.mat", "table_accounting", '-append')
disp('***')

% (v) alt model 1b: no OJS
disp('Alt model 1b (no OJS)')
load("Results\alternative_models\model_1b.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\alternative_models\model_1b.mat", "table_accounting", '-append')
disp('***')

% (v) alt model 3b: no worker, job het, no OJS
disp('Alt model 3b (no worker/job het., no OJS)')
load("Results\alternative_models\model_3b.mat", "parameters", "moments")
[table_accounting] = accounting_table(parameters, moments, data);
save("Results\alternative_models\model_3b.mat", "table_accounting", '-append')
disp('***')

%% 3. Parameter table

% 1. US parameters
A = zeros(1,4);
b = zeros(1,4);
lambda = zeros(1,4);
s = zeros(1,4);
b_w = zeros(1,4);

% 2. Counterfactual policy parameters
A1 = zeros(1,4);
b1 = zeros(1,4);
tax1 = zeros(1,4);
F1 = zeros(1,4);

% fill in 
for jj  = 1:4
    
    % Benchmark
    if jj == 1
        filename = "Results\Benchmark.mat";

        % alternative models
    elseif jj == 2
        filename = "Results\alternative_models\model_1.mat";
        
    elseif jj == 3
        filename = "Results\alternative_models\model_2.mat";

    else
        filename = "Results\alternative_models\model_3.mat";
    end

    load( filename, "parameters", "moments", "table_accounting")

    A(jj) = parameters.A;
    b(jj) = parameters.b;
    lambda(jj) = parameters.lambda;
    s(jj) = parameters.s;

    b_w(jj) = moments.agg.b_w;
    
    A1(jj) = table_accounting.A(3);
    b1(jj) = table_accounting.b(2);
    tax1(jj) = table_accounting.tax(2);
    F1(jj) = table_accounting.F(2);

end

% lines
tmp_mat = [A; b; lambda; s; b_w; A1; b1; tax1; F1];
line = @(ii, fmt) [ num2str(tmp_mat(ii,1), fmt), ' & ',  num2str(tmp_mat(ii,2), fmt), ' & ',...
                    num2str(tmp_mat(ii,3), fmt), ' & ', num2str(tmp_mat(ii,4), fmt) ' \\\\'  ];


% table
fmt1 = '%.2f';

Table_5 = [ ...
'\\begin{table}[!h]'        '\n' ...
'\\small'        '\n' ...
'\\centering'        '\n' ...
'\\captionof{table}{Parameters in calibrated alternative models}'        '\n' ...
'\\label{tab:table_5}'        '\n' ...
'\\begin{tabular}{l c c c c c}'        '\n' ...
'\\hline \\hline'        '\n' ...
'\\addlinespace'         '\n' ...
'          &     &  & \\multicolumn{3}{c}{Alternative models}                         \\\\'       '\n' ...
'          &  \\hspace{80pt}  & \\text{Benchmark} & \\text{(i)} & \\text{(ii)}  & \\text{(iii)}    \\\\'        '\n' ...
'\\addlinespace'        '\n' ...
'\\textit{U.S.\\ calibration} \\\\'    '\n' ...
'\\addlinespace'        '\n' ...
'$A$ & &',            line(1,fmt1)  '\n' ...
'$b$ & &',            line(2,fmt1)  '\n' ...
'$\\lambda$ & &',     line(3,fmt1)  '\n' ...
'$\\xi$ & &',         line(4,fmt1)  '\n' ...
'$\\zeta$ & &'        line(5,fmt1)  '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\textit{European policies} \\\\'    '\n' ...
'\\addlinespace'        '\n' ...
'$A$ & &',            line(6,fmt1)  '\n' ...
'$b$ & &',            line(7,fmt1)  '\n' ...
'$\\phi$ & &',        line(8,fmt1)  '\n' ...
'$F$ & &',            line(9,fmt1)  '\n' ...
'\\addlinespace' '\n' ...
'\\addlinespace' '\n' ...
'\\hline \\hline'        '\n' ...
'\\end{tabular}'         '\n' ...
'\\caption*{\\footnotesize{\\textit{Note:} ',  '\n' ...
'parameter values in models with alternative heterogeneity specifications. The table also reports equilibrium effective unemployment income replacement ratio $\\zeta$. ' '\n' ...
'Benchmark: full quantitative model. Alternative model (i): no worker skill heterogeneity; (ii) no permanent match-quality (job) heterogeneity; ' '\n' ...
'(iii) no worker nor job heterogeneity. \\textit{U.S.\\ calibration} refers to the calibration to the U.S.\\ labor-market flows and \\textit{European policies} refers to the calibration with policy targets averaged across France, Germany, Italy, Spain, and Portugal discussed in the main text. ' '\n' ...
'$A$; matching efficiency; $b$: non-work utility; $\\lambda$: probability of match-specific productivity shock; $\\xi$: employment-search relative matching efficiency; ' '\n' ...
'$\\phi$: match-output proportional tax; $F$: firing costs.}}' '\n' ...
'\\end{table}' ];

% Export tables
tables_path = [results_path,'\Tables\'];
fileID = fopen([tables_path, 'Table_5.tex'],'w');
fprintf(fileID, Table_5);
fclose(fileID);


%% 4 Result table

% number of alternative models 
L = 6;

% initialize
UE = struct;
UE.policies = zeros(1,L);
UE.firing_costs = zeros(1,L);
UE.ub_tax = zeros(1,L);
UE.matching_efficiency = zeros(1,L);
UE.residual = zeros(1,L);

EU = struct;
EU.policies = zeros(1,L);
EU.firing_costs = zeros(1,L);
EU.ub_tax = zeros(1,L);
EU.matching_efficiency = zeros(1,L);
EU.residual = zeros(1,L);

% total relative difference
UE.total = ( data.calibration_targets.ue_Eur - data.calibration_targets.ue_US )/data.calibration_targets.ue_US;
EU.total = ( data.calibration_targets.eu_Eur - data.calibration_targets.eu_US )/data.calibration_targets.eu_US;


% fill in
for jj  = 1:L
    
    % Benchmark
    if jj == 1
        filename = "Results\Benchmark.mat";

        % alternative models
    elseif jj == 2
        filename = "Results\alternative_models\model_1.mat";
        
    elseif jj == 3
        filename = "Results\alternative_models\model_2.mat";

    elseif jj == 4
        filename = "Results\alternative_models\model_3.mat";

    elseif jj == 5
        filename = "Results\alternative_models\model_1b.mat";

    elseif jj == 6
        filename = "Results\alternative_models\model_3b.mat";

    end

    load( filename, "table_accounting")

    % UE contributions
    UE.policies(jj)             = ( table_accounting.ue(2) / table_accounting.ue(1) - 1 ) / UE.total;
    UE.firing_costs(jj)         = ( table_accounting.ue(4) / table_accounting.ue(1) - 1)  / UE.total;
    UE.ub_tax(jj)               = ( table_accounting.ue(5) / table_accounting.ue(1) - 1)  / UE.total;
    UE.matching_efficiency(jj)  = ( (table_accounting.ue(3) - table_accounting.ue(2)) / table_accounting.ue(1) )  / UE.total;
    
    % UE, residual
    total_explained = ( table_accounting.ue(3) / table_accounting.ue(1) - 1)  / UE.total;
    UE.residual(jj) = 1 - total_explained;

    % EU contributions
    EU.policies(jj)             = ( table_accounting.eu(2) / table_accounting.eu(1) - 1 ) / UE.total;
    EU.firing_costs(jj)         = ( table_accounting.eu(4) / table_accounting.eu(1) - 1)  / UE.total;
    EU.ub_tax(jj)               = ( table_accounting.eu(5) / table_accounting.eu(1) - 1)  / UE.total;
    EU.matching_efficiency(jj)  = ( (table_accounting.eu(3) - table_accounting.eu(2))  / table_accounting.eu(1) )  / UE.total;
    
    % EU residual
    total_explained = ( table_accounting.eu(3) / table_accounting.eu(1) - 1)  / UE.total;
    EU.residual(jj) = 1 - total_explained;

end


%% 4.1. Accounting: models with OJS

% lines
tmp_mat = [UE.policies; UE.firing_costs; UE.ub_tax; UE.matching_efficiency; UE.residual; ...
           EU.policies; EU.firing_costs; EU.ub_tax; EU.matching_efficiency; EU.residual]*100;

line = @(ii, fmt) [ num2str(tmp_mat(ii,1), fmt), ' & ',  num2str(tmp_mat(ii,2), fmt), ' & ',...
                    num2str(tmp_mat(ii,3), fmt), ' & ',  num2str(tmp_mat(ii,4), fmt) ' \\\\'  ];

line_it = @(ii, fmt) [ '\\textit{' num2str(tmp_mat(ii,1), fmt) '}', ' & ', '\\textit{'  num2str(tmp_mat(ii,2), fmt) '}', ' & ',...
                       '\\textit{' num2str(tmp_mat(ii,3), fmt) '}', ' & ',  '\\textit{' num2str(tmp_mat(ii,4), fmt) '}', ' \\\\'  ];

fmt1 = '%.1f';

Table_6 = [ ...
'\\begin{table}[!h]'        '\n' ...
'\\small'        '\n' ...
'\\centering'        '\n' ...
'\\captionof{table}{Sources of U.S.-Europe differences in unemployment flows in alternative models}'        '\n' ...
'\\label{tab:table_6}'        '\n' ...
'\\begin{tabular}{l c c c c c}'        '\n' ...
'\\hline \\hline'        '\n' ...
'\\addlinespace'         '\n' ...
'          &     &  & \\multicolumn{3}{c}{Alternative models}                         \\\\'       '\n' ...
'          &  \\hspace{80pt}  & \\text{Benchmark} & \\text{(i)} & \\text{(ii)}  & \\text{(iii)}    \\\\'        '\n' ...
'\\addlinespace'         '\n' ...
'UE rate, contribution (\\%%) \\\\'  '\n' ...
'\\addlinespace'         '\n' ...
'\\hspace{4pt} Policies            & &', line(1,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Firing costs}       &  &', line_it(2,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Unem. benefits and taxes}       &  &', line_it(3,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{4pt} Matching efficiency & &', line(4,fmt1), '\n' ...
'\\hspace{4pt} Residual            & &', line(5,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'EU rate, contribution (\\%%) \\\\' '\n' ...
'\\addlinespace'         '\n' ...
'\\hspace{4pt} Policies            & &', line(6,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Firing costs}       &  &', line_it(7,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Unem. benefits and taxes}       &  &', line_it(8,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{4pt} Matching efficiency &  &', line(9,fmt1), '\n' ...
'\\hspace{4pt} Residual            &  &', line(10,fmt1), '\n' ...
'\\addlinespace' '\n' ...
'\\addlinespace' '\n' ...
'\\hline \\hline'        '\n' ...
'\\end{tabular}'         '\n' ...
'\\caption*{\\footnotesize{\\textit{Note:}',  '\n' ...
'policy and matching-efficiency contribution to relative differences in cross-country UE and EU flows across models with alternative heterogeneity specifications. ' '\n' ...
'Benchmark: full quantitative model. Alternative model (i): no worker skill heterogeneity; (ii) no permanent match-quality (job) heterogeneity; ' '\n' ...
'(iii) no worker nor job heterogeneity. Policies: combined contribution of firing costs, non-work utility and taxes implied by parameter differences in table \\ref{tab:table_5}. ' '\n' ...
'\\textit{Firing costs}: contribution of firing costs, in isolation. \\textit{Unem. benefits and taxes}: combined contribution of unemployment benefits and taxes together. ' '\n' ...
'Matching efficiency: marginal contribution of matching-efficiency differences (table \\ref{tab:table_5}) given policy differences. Residual: relative difference in flows after imposing policy and matching-efficiency variation. See main text for additional details.}}' '\n' ...
'\\end{table}' ];


% Export table to latex files
fileID = fopen([tables_path, 'Table_6.tex'],'w');
fprintf(fileID, Table_6);
fclose(fileID);



%% 4.2. Accounting: model without OJS

line = @(ii, fmt) [ '\\textit{' num2str(tmp_mat(ii,1), fmt) '}', ' &  &', num2str(tmp_mat(ii,5), fmt), ' & ',  num2str(tmp_mat(ii,6), fmt), ' \\\\'  ];
line_it = @(ii, fmt) [ '\\textit{' num2str(tmp_mat(ii,1), fmt) '}', ' &  &', '\\textit{' num2str(tmp_mat(ii,5), fmt) '}', ' & ', '\\textit{'  num2str(tmp_mat(ii,6), fmt) '}', ' \\\\'  ];

Table_8 = [ ...
'\\begin{table}[!h]'        '\n' ...
'\\small'        '\n' ...
'\\centering'        '\n' ...
'\\captionof{table}{Sources of U.S.-Europe differences in unemployment flows in models without OJS}'        '\n' ...
'\\label{tab:table_7}'        '\n' ...
'\\begin{tabular}{l c c c c c}'        '\n' ...
'\\hline \\hline'        '\n' ...
'\\addlinespace'         '\n' ...
'          &     &  & \\multicolumn{3}{c}{Alternative models}                         \\\\'       '\n' ...
'          &  \\hspace{80pt}  & \\text{Benchmark} & \\hspace{8pt} & \\text{(iv)} & \\text{(v)}  \\\\'        '\n' ...
'\\addlinespace'         '\n' ...
'UE rate, contribution (\\%%) \\\\'  '\n' ...
'\\addlinespace'         '\n' ...
'\\hspace{4pt} Policies            & &', line(1,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Firing costs}       &  &', line_it(2,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Unem. benefits and taxes}       &  &', line_it(3,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{4pt} Matching efficiency & &', line(4,fmt1), '\n' ...
'\\hspace{4pt} Residual            & &', line(5,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'\\addlinespace'        '\n' ...
'EU rate, contribution (\\%%) \\\\' '\n' ...
'\\addlinespace'         '\n' ...
'\\hspace{4pt} Policies            & &', line(6,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Firing costs}       &  &', line_it(7,fmt1), '\n' ...
'\\hspace{8pt} \\textit{Unem. benefits and taxes}       &  &', line_it(8,fmt1), '\n' ...
'\\addlinespace'        '\n' ...
'\\hspace{4pt} Matching efficiency &  &', line(9,fmt1),  '\n' ...
'\\hspace{4pt} Residual            &  &', line(10,fmt1), '\n' ...
'\\addlinespace' '\n' ...
'\\addlinespace' '\n' ...
'\\hline \\hline'        '\n' ...
'\\end{tabular}'         '\n' ...
'\\caption*{\\footnotesize{\\textit{Note:}',  '\n' ...
'policy and matching-efficiency contribution to relative differences in cross-country UE and EU flows across models with alternative heterogeneity specifications. ' '\n' ...
'Benchmark: full quantitative model. Alternative model (iv): no on-the-job search; ' '\n' ...
'(v) no worker nor job heterogeneity and no OJS. Policies: combined contribution of firing costs, non-work utility and taxes implied by parameter differences in table 5.' '\n' ...
'\\textit{Firing costs}: contribution of firing costs, in isolation. \\textit{Unem. benefits and taxes}: combined contribution of unemployment benefits and taxes together. ' '\n' ...
'Matching efficiency: marginal contribution of matching-efficiency differences (table 5) given policy differences. Residual: relative difference in flows after imposing policy and matching-efficiency variation. See main text for additional details.}}' '\n' ...
'\\end{table}' ];


% Export table to latex files
fileID = fopen([tables_path, 'Table_8.tex'],'w');
fprintf(fileID, Table_8);
fclose(fileID);

%%
disp('Accounting: done. Check latex files.')

